spring.application.name=RESTful_API
spring.datasource.url=jdbc:mysql://localhost:3306/my_database?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=5681946352445Qq^
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
